import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Support Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button className="px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700">
        Support Chat App
      </button>
      <div className='p-2 text-3xl text-green-600'>
      Hello Geeks!
    </div>
    <button className="px-8 py-4 font-bold tracking-wider text-white uppercase bg-indigo-500 rounded-full shadow-lg focus:outline-none">
        Clicketh the button
      </button>
    </>
  );
};

export default Home;


